### ISSUE TITLE
Yay! I want to see it!

### ISSUE THREAD

**Issue by vctormb** [cassette-tape/cassette-tape-react-native#1]
I've watched your React Conf video and it was awesome!
Can't wait to see this code right here :)

**Comment by miukimiu** [comment]
@vctormb the code that I used at React Conf was this one:
https://github.com/miukimiu/react-cassette-tape (I only tested on Chrome).

But I met @frontvu during the Conf and he had the idea to do a React Native version. So I created this new project!

**Comment by frontvu** [comment]
Yeah, I'm excited to see what we can do with cassette and react native. @miukimiu, let's get a plan together.

**Comment by miukimiu** [comment]
@frontvu, cool!

I'm going to create the design that I have in mind and then I share with you! 😄
